
package UserInterface.TravelAgency;

import Business.Airliner.Airliner;
import Business.Airliner.Fleet.Airplane;
import Business.Airliner.Flight.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author SUNREN
 */
public class ViewAirlinerJPanel extends javax.swing.JPanel {

    private Airliner airliner;
    private JPanel cardSequenceJPanel;
    
    public ViewAirlinerJPanel(Airliner airliner, JPanel cardSequenceJPanel) {
        initComponents();
        this.airliner = airliner;
        this.cardSequenceJPanel = cardSequenceJPanel;
        
        init();
                
    }
    
    private void init(){
        this.indexjTextField.setEditable(false);
        this.namejTextField.setEditable(false);
        this.modifyjButton.setEnabled(true);
        this.savejButton.setEnabled(false);
        this.indexjTextField.setText(airliner.getId());
        this.namejTextField.setText(airliner.getName());
        populateAirPlaneTable();
        populateFlightTable();
        
        
    }
    
    private void populateAirPlaneTable(){
        DefaultTableModel dfm = (DefaultTableModel)airplanejTable.getModel();
        dfm.setRowCount(0);
        airliner.getAirplaneDirectory().getAirplaneList().forEach((Airplane airplane)->{
            Object[] row = new Object[dfm.getColumnCount()];
            row[0] = airplane.getName();
            row[1] = airplane.getSeatNumber();
            row[2] = airplane.getSerialNum();
            
            dfm.addRow(row);
        });
        
    }
    
    private void populateFlightTable(){
        DefaultTableModel dfm = (DefaultTableModel)flightsjTable2.getModel();
        dfm.setRowCount(0);
        airliner.getFlightSchedual().getFlghtList().forEach((Flight flight)->{
            Object[] row = new Object[dfm.getColumnCount()];
            row[0] = flight.getFlightNo();
            row[1] = flight.getDeparture();
            row[2] = flight.getDestination();
            row[3] = flight.getDate();
            row[4] = flight.getStartTime().format(DateTimeFormatter.ISO_TIME);
            row[5] = flight.getArriveTime().format(DateTimeFormatter.ISO_TIME);
            row[6] = flight.getPrice() + "";
            
            dfm.addRow(row);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        airplanejTable = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        flightsjTable2 = new javax.swing.JTable();
        backjButton = new javax.swing.JButton();
        modifyjButton = new javax.swing.JButton();
        namejTextField = new javax.swing.JTextField();
        indexjTextField = new javax.swing.JTextField();
        savejButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Index：");

        jLabel2.setText("Name：");

        airplanejTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model Number", "Seat Number", "Serial Number"
            }
        ));
        jScrollPane1.setViewportView(airplanejTable);

        jLabel3.setText("Flights:");

        jLabel4.setText("Airplanes:");

        flightsjTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Number", "Departure", "Destination", "Date", "Start Time", "Arrive Time", "Price"
            }
        ));
        jScrollPane2.setViewportView(flightsjTable2);

        backjButton.setText("Back");
        backjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backjButtonActionPerformed(evt);
            }
        });

        modifyjButton.setText("Modify");
        modifyjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyjButtonActionPerformed(evt);
            }
        });

        namejTextField.setEditable(false);

        indexjTextField.setEditable(false);
        indexjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                indexjTextFieldActionPerformed(evt);
            }
        });

        savejButton.setText("Save");
        savejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savejButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 153, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(backjButton)
                            .addGap(350, 350, 350)
                            .addComponent(modifyjButton)
                            .addGap(25, 25, 25)
                            .addComponent(savejButton))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel1)
                            .addGap(32, 32, 32)
                            .addComponent(indexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jLabel2)
                            .addGap(38, 38, 38)
                            .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel4))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(150, 150, 150)
                            .addComponent(jLabel3))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 153, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 88, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(backjButton)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(7, 7, 7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(modifyjButton)
                                .addComponent(savejButton))))
                    .addGap(2, 2, 2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel1))
                        .addComponent(indexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(14, 14, 14)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(5, 5, 5)
                            .addComponent(jLabel2))
                        .addComponent(namejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jLabel4)
                    .addGap(7, 7, 7)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(6, 6, 6)
                    .addComponent(jLabel3)
                    .addGap(7, 7, 7)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 88, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backjButtonActionPerformed
        // TODO add your handling code here:
        CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
        cardSequenceJPanel.remove(this);
        layout.previous(cardSequenceJPanel);

        Component[] comps = cardSequenceJPanel.getComponents();
        for(Component comp : comps){
            if(comp instanceof ManageAirlinerJPanel){
                ManageAirlinerJPanel manage = (ManageAirlinerJPanel)comp;
                manage.populate();
            }
        }

    }//GEN-LAST:event_backjButtonActionPerformed

    private void modifyjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyjButtonActionPerformed
        // TODO add your handling code here:
        this.modifyjButton.setEnabled(false);
        this.namejTextField.setEditable(true);
        this.savejButton.setEnabled(true);
    }//GEN-LAST:event_modifyjButtonActionPerformed

    private void indexjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_indexjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_indexjTextFieldActionPerformed

    private void savejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savejButtonActionPerformed
        // TODO add your handling code here:
        String name = namejTextField.getText();
        if(name.equals(null)||name.startsWith(" ")){
            JOptionPane.showMessageDialog(null, "Please do not input name start with space");
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(airliner.getName());
        }else if(name.equals(airliner.getName())){
            JOptionPane.showMessageDialog(null, "It is the same as before, nothing modified");
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(airliner.getName());
        }else{
            JOptionPane.showMessageDialog(null, "Modified Successfully");
            airliner.setName(name);
            this.modifyjButton.setEnabled(true);
            this.namejTextField.setEditable(false);
            this.savejButton.setEnabled(false);
            this.namejTextField.setText(airliner.getName());
        }
    }//GEN-LAST:event_savejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable airplanejTable;
    private javax.swing.JButton backjButton;
    private javax.swing.JTable flightsjTable2;
    private javax.swing.JTextField indexjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton modifyjButton;
    private javax.swing.JTextField namejTextField;
    private javax.swing.JButton savejButton;
    // End of variables declaration//GEN-END:variables
}
