
package UserInterface.TravelOffice;
import Business.Airliner.Airliner;
import Business.Airliner.Flight.Flight;
import Business.MasterTravelSchedule;
import Business.Ticket.TicketDirectory;
import Business.TravelAgency.TravelAgency;
import Business.TravelOffice.Customer.Customer;
import Business.TravelOffice.TravelOffice;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 25434
 */
public class BookTicketJPanel extends javax.swing.JPanel {

    private TicketDirectory ticketDirectory;
    private JPanel cardSequenceJPanel;
    private TravelOffice travelOffice;
    private List<Flight> FlightList;
    
   public BookTicketJPanel(JPanel cardSequenceJPanel, TravelOffice travelOffice) {
        initComponents();
        this.travelOffice = travelOffice;
        this.cardSequenceJPanel = cardSequenceJPanel;
        this.FlightList = MasterTravelSchedule.getInstance().getAllFlightsOfAirliners();
        populateCustomer(travelOffice.getCustomerDirectory().getCustomerList());
        populateFlight(FlightList);
        flightCombox.setModel(new DefaultComboBoxModel(FlightList.toArray())); 
        List<String> departureList = new ArrayList<>();
        List<String> tempListD = new ArrayList<>();
        FlightList.forEach(flight ->{
                    tempListD.add(flight.getDeparture());});
        Set<String> tempSet = tempListD.stream()
                .collect(Collectors.toSet());
        tempSet.forEach(a -> {
            departureList.add(a);
        });
        
        
        departLocationComBox.setModel(new DefaultComboBoxModel(departureList.toArray())); 
        
        List<String> arraivalList = new ArrayList<>();
        List<String> tempListA = new ArrayList<>();
       FlightList.forEach(flight ->{
                    tempListA.add(flight.getDestination());});
        Set<String> tempSetA = tempListA.stream()
                .collect(Collectors.toSet());
        tempSetA.forEach(a -> {
            arraivalList.add(a);
        });
        
        ArrivalLocationComBox1.setModel(new DefaultComboBoxModel(arraivalList.toArray())); 
        
         List<String> dateList = new ArrayList<>();
        List<String> tempListDate = new ArrayList<>();
        FlightList.forEach(flight ->{
                    tempListDate.add(flight.getDate());});
        Set<String> tempSetDate = tempListDate.stream()
                .collect(Collectors.toSet());
        tempSetDate.forEach(a -> {
            dateList.add(a);
        });
        
        dataComBox.setModel(new DefaultComboBoxModel(dateList.toArray())); 
        
        
        TimeZoneComBox.setModel(new DefaultComboBoxModel(new String[]{"Morning","DayTime","Evening"}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        customerJTable = new javax.swing.JTable();
        Createcustbtn = new javax.swing.JButton();
        findPreferBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        flightJTable = new javax.swing.JTable();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        departLocationComBox = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        ArrivalLocationComBox1 = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TimeZoneComBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        flightCombox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        dataComBox = new javax.swing.JComboBox<>();
        dateRadioBtn = new javax.swing.JRadioButton();
        flightRadioBtn = new javax.swing.JRadioButton();
        flightSearchRedio2 = new javax.swing.JRadioButton();
        departureRadioBtn = new javax.swing.JRadioButton();
        TimeZoneRadioBtn = new javax.swing.JRadioButton();
        ArrivalRadioBtn = new javax.swing.JRadioButton();
        choseSeatBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setText("Booking Ticket");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 22, -1, -1));

        customerJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Membership ID", "Identity ID", "Office Info"
            }
        ));
        jScrollPane2.setViewportView(customerJTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 750, 90));

        Createcustbtn.setBackground(new java.awt.Color(255, 255, 255));
        Createcustbtn.setText("Create New Customer");
        Createcustbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatecustbtnActionPerformed(evt);
            }
        });
        add(Createcustbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, -1));

        findPreferBtn.setBackground(new java.awt.Color(255, 255, 255));
        findPreferBtn.setText("Find Flight");
        findPreferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findPreferBtnActionPerformed(evt);
            }
        });
        add(findPreferBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 200, -1));

        flightJTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Flight #", "Airplane #", "Time", "Departure", "Arrival", "Date"
            }
        ));
        jScrollPane1.setViewportView(flightJTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 750, 90));

        backBtn.setBackground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.setToolTipText("");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, 210, -1));

        jLabel3.setText("Departure:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, 20));

        departLocationComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(departLocationComBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, 20));

        jLabel4.setText("Arrival:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 50, 20));

        ArrivalLocationComBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(ArrivalLocationComBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, -1, -1));

        jLabel5.setText("TimeZone:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 80, 20));

        TimeZoneComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        TimeZoneComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TimeZoneComBoxActionPerformed(evt);
            }
        });
        add(TimeZoneComBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, -1, -1));

        jLabel6.setText("Flight #:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, -1, 20));

        flightCombox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(flightCombox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 80, -1));

        jLabel7.setText("Date:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 240, -1, 20));

        dataComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(dataComBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 70, -1));
        add(dateRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 240, -1, -1));
        add(flightRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));
        add(flightSearchRedio2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));
        add(departureRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, -1, 20));
        add(TimeZoneRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 240, -1, -1));
        add(ArrivalRadioBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        choseSeatBtn.setBackground(new java.awt.Color(255, 255, 255));
        choseSeatBtn.setText("Choose a Seat");
        choseSeatBtn.setMaximumSize(new java.awt.Dimension(170, 23));
        choseSeatBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choseSeatBtnActionPerformed(evt);
            }
        });
        add(choseSeatBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 280, 210, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void CreatecustbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatecustbtnActionPerformed
        // TODO add your handling code here:
        Customer customer = new Customer(travelOffice);
        CreateNewCustJPanel panel = new CreateNewCustJPanel(cardSequenceJPanel, customer, travelOffice.getCustomerDirectory());
        cardSequenceJPanel.add(panel);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_CreatecustbtnActionPerformed

    public void populateCustomer(List<Customer> customerList){
        DefaultTableModel dtm = (DefaultTableModel)customerJTable.getModel();
        dtm.setRowCount(0);
        
        customerList.forEach((Customer customer) -> {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = customer;
            row[1] = customer.getId();
            row[2] = customer.getIdentityType() + customer.getIdentityID();
            row[3] = customer.getOfficeInfo();
            dtm.addRow(row);
        });
    }
    
    public void populateFlight(List<Flight> flightList){
        DefaultTableModel dtm = (DefaultTableModel)flightJTable.getModel();
        dtm.setRowCount(0);
        
        flightList.forEach((Flight flight) -> {
            Object[] row = new Object[dtm.getColumnCount()];
            row[0] = flight;
            row[1] = flight.getAirplane().getSerialNum();
            row[2] = flight.getStartTime();
            row[3] = flight.getDeparture();
            row[4] = flight.getDestination();
            row[5] = flight.getDate();
            dtm.addRow(row);
        });
    }

    
    
    private void findPreferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findPreferBtnActionPerformed
        // TODO add your handling code here:
        if(flightRadioBtn.isSelected()){
            populateFlight(MasterTravelSchedule.getInstance().searchFlightsByFlightNum(flightCombox.getSelectedItem().toString()));
        }else if ((dateRadioBtn.isSelected())
            && (!departureRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString()));
        }else if ((departureRadioBtn.isSelected())
            && (!dateRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByDeparture(this.FlightList, departLocationComBox.getSelectedItem().toString()));
        }else if (ArrivalRadioBtn.isSelected()
            && (!departureRadioBtn.isSelected())
            && (!dateRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByArrival(this.FlightList, ArrivalLocationComBox1.getSelectedItem().toString()));
        }else if (TimeZoneRadioBtn.isSelected()
            && (!departureRadioBtn.isSelected())
            && (!dateRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())){
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(this.FlightList, TimeZoneComBox.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByDeparture(searchList, departLocationComBox.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (!departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByArrival(searchList, ArrivalLocationComBox1.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (!departureRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList, TimeZoneComBox.getSelectedItem().toString()));
        }else if((!dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList = MasterTravelSchedule.getInstance().searchFlightByDeparture(this.FlightList, departLocationComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByArrival(searchList, ArrivalLocationComBox1.getSelectedItem().toString()));
        }else if((!dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList = MasterTravelSchedule.getInstance().searchFlightByDeparture(this.FlightList, departLocationComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList, TimeZoneComBox.getSelectedItem().toString()));
        }else if((!dateRadioBtn.isSelected())
            && (!departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList = MasterTravelSchedule.getInstance().searchFlightByArrival(this.FlightList, ArrivalLocationComBox1.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList, TimeZoneComBox.getSelectedItem().toString()));
        }else if((!dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList1 = MasterTravelSchedule.getInstance().searchFlightByDeparture(this.FlightList, departLocationComBox.getSelectedItem().toString());
            List<Flight> searchList2 = MasterTravelSchedule.getInstance().searchFlightByArrival(searchList1, ArrivalLocationComBox1.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList2, TimeZoneComBox.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (!departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList1 = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            List<Flight> searchList2 = MasterTravelSchedule.getInstance().searchFlightByArrival(searchList1, ArrivalLocationComBox1.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList2, TimeZoneComBox.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (!ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList1 = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            List<Flight> searchList2 = MasterTravelSchedule.getInstance().searchFlightByDeparture(searchList1, departLocationComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList2, TimeZoneComBox.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (!TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList1 = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            List<Flight> searchList2 = MasterTravelSchedule.getInstance().searchFlightByDeparture(searchList1, departLocationComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByArrival(searchList2, ArrivalLocationComBox1.getSelectedItem().toString()));
        }else if((dateRadioBtn.isSelected())
            && (departureRadioBtn.isSelected())
            && (ArrivalRadioBtn.isSelected())
            && (TimeZoneRadioBtn.isSelected())){
            List<Flight> searchList1 = MasterTravelSchedule.getInstance().searchFlightByDate(this.FlightList, dataComBox.getSelectedItem().toString());
            List<Flight> searchList2 = MasterTravelSchedule.getInstance().searchFlightByDeparture(searchList1, departLocationComBox.getSelectedItem().toString());
            List<Flight> searchList3 = MasterTravelSchedule.getInstance().searchFlightByTimeRange(searchList2, TimeZoneComBox.getSelectedItem().toString());
            populateFlight((List<Flight>) MasterTravelSchedule.getInstance().searchFlightByArrival(searchList3, ArrivalLocationComBox1.getSelectedItem().toString()));
        }
    }//GEN-LAST:event_findPreferBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void TimeZoneComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TimeZoneComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TimeZoneComBoxActionPerformed

    private void choseSeatBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choseSeatBtnActionPerformed
        // TODO add your handling code here:
        int selectedFlight = flightJTable.getSelectedRow();
        int selectedCustomer = customerJTable.getSelectedRow();

        if(selectedFlight < 0 || selectedCustomer<0){
            JOptionPane.showMessageDialog(null, "Please select a row!");
        }else{
            Flight flight = (Flight) flightJTable.getValueAt(selectedFlight, 0);
            Customer customer = (Customer) customerJTable.getValueAt(selectedCustomer, 0);

            SelectSeatJPanel panel = new SelectSeatJPanel(cardSequenceJPanel,flight, customer,travelOffice);
            cardSequenceJPanel.add(panel);
            CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
            layout.next(cardSequenceJPanel);
        }
    }//GEN-LAST:event_choseSeatBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ArrivalLocationComBox1;
    private javax.swing.JRadioButton ArrivalRadioBtn;
    private javax.swing.JButton Createcustbtn;
    private javax.swing.JComboBox<String> TimeZoneComBox;
    private javax.swing.JRadioButton TimeZoneRadioBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton choseSeatBtn;
    private javax.swing.JTable customerJTable;
    private javax.swing.JComboBox<String> dataComBox;
    private javax.swing.JRadioButton dateRadioBtn;
    private javax.swing.JComboBox<String> departLocationComBox;
    private javax.swing.JRadioButton departureRadioBtn;
    private javax.swing.JButton findPreferBtn;
    private javax.swing.JComboBox<String> flightCombox;
    private javax.swing.JTable flightJTable;
    private javax.swing.JRadioButton flightRadioBtn;
    private javax.swing.JRadioButton flightSearchRedio2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
