/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import Business.Airliner.Airliner;
import Business.Airliner.AirlinerDirectory;
import Business.Airliner.Flight.Flight;
import Business.Airliner.Flight.FlightSchedual;
import Business.UserAccount.UserAccount;
import UserInterface.Airliner.ManageFlightJPanel;
import UserInterface.Airliner.ManageFlightJPanel;
import UserInterface.Airliner.ViewOrderedTicketsJPanel;
import UserInterface.Airliner.ViewOrderedTicketsJPanel;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Alex Zhu
 */
public class AirlinerSplitLifeJPanel extends javax.swing.JPanel {

    
    public FlightSchedual flightList;
    public AirlinerDirectory airlinerList;
    private JPanel cardSequenceJPanel;
    private UserAccount userAccount;
    private Airliner airliner;
    public AirlinerSplitLifeJPanel(UserAccount userAccount,JPanel cardSequenceJPanel) {
        initComponents();
        this.userAccount = userAccount;
        this.airliner = (Airliner) userAccount.getMember();
        this.cardSequenceJPanel = cardSequenceJPanel;
        initialize();
    }
    public void initialize(){
        nameTxt.setText(userAccount.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameTxt = new javax.swing.JLabel();
        btnManage = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnViewTicket = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        nameTxt.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        nameTxt.setText("Airliner name:");
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, -1, 40));

        btnManage.setBackground(new java.awt.Color(255, 255, 255));
        btnManage.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnManage.setText("Manage Flight");
        btnManage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageActionPerformed(evt);
            }
        });
        add(btnManage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, 40));

        jLabel6.setBackground(new java.awt.Color(204, 204, 204));
        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Welcome to");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, 40));

        btnViewTicket.setBackground(new java.awt.Color(255, 255, 255));
        btnViewTicket.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnViewTicket.setText("View  Tickets");
        btnViewTicket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewTicketActionPerformed(evt);
            }
        });
        add(btnViewTicket, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 180, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageActionPerformed
        // TODO add your handling code here:
        FlightSchedual fls =airliner.getFlightSchedual();
        ManageFlightJPanel panel = new ManageFlightJPanel(cardSequenceJPanel,airliner);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        cardSequenceJPanel.add(panel);
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnManageActionPerformed

    private void btnViewTicketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewTicketActionPerformed
        // TODO add your handling code here:
        ViewOrderedTicketsJPanel view = new ViewOrderedTicketsJPanel(cardSequenceJPanel, airliner);
        cardSequenceJPanel.add(view);
        CardLayout layout = (CardLayout)cardSequenceJPanel.getLayout();
        layout.next(cardSequenceJPanel);
    }//GEN-LAST:event_btnViewTicketActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManage;
    private javax.swing.JButton btnViewTicket;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel nameTxt;
    // End of variables declaration//GEN-END:variables
}
