/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Sysadmin;

/**
 *
 * @author Alex Zhu
 */
public class UserAdminMain extends javax.swing.JPanel {

    /**
     * Creates new form CarRentCompanyMain
     */
    public UserAdminMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLesee = new javax.swing.JButton();
        btnDriver = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnLesor = new javax.swing.JButton();

        btnLesee.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLesee.setText("Lessee Manage");

        btnDriver.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnDriver.setText("Driver Manage");

        jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
        jLabel1.setText("User Admin");

        btnLesor.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnLesor.setText("Lessor Manage");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDriver, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(367, 367, 367)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(346, 346, 346)
                            .addComponent(btnLesee)))
                    .addComponent(btnLesor, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(387, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addGap(86, 86, 86)
                .addComponent(btnLesee)
                .addGap(18, 18, 18)
                .addComponent(btnLesor)
                .addGap(18, 18, 18)
                .addComponent(btnDriver)
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDriver;
    private javax.swing.JButton btnLesee;
    private javax.swing.JButton btnLesor;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
