
package UserInterface.TravelOffice;
import Business.Airliner.Flight.Flight;
import Business.Ticket.Ticket;
import Business.TravelOffice.Customer.Customer;
import Business.TravelOffice.TravelOffice;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
/**
 *
 * @author 25434
 */
public class SelectSeatJPanel extends javax.swing.JPanel {

    private Flight flight;
    private Customer customer;
    private TravelOffice travelOffice;
    private JPanel cardSequenceJPanel;
    
    SelectSeatJPanel(JPanel cardSequenceJPanel,Flight flight, Customer customer, TravelOffice travelOffice) {
        initComponents();
        this.flight = flight;
        this.customer = customer;
        this.travelOffice = travelOffice;
        this.cardSequenceJPanel = cardSequenceJPanel;
        List<String> flightSort = this.flight.getAvaliableSeat();
        Collections.sort(flightSort);
        SeatNumberComBox.setModel(new DefaultComboBoxModel(flightSort.toArray()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        SeatNumberComBox = new javax.swing.JComboBox<>();
        ConfrimtBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Avaliable Seat:");

        SeatNumberComBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SeatNumberComBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatNumberComBoxActionPerformed(evt);
            }
        });

        ConfrimtBtn.setText("Confirm");
        ConfrimtBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfrimtBtnActionPerformed(evt);
            }
        });

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel3.setText("Choose A Seat");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(171, 171, 171)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ConfrimtBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SeatNumberComBox, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(120, 120, 120))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(SeatNumberComBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ConfrimtBtn)
                .addGap(18, 18, 18)
                .addComponent(backBtn)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SeatNumberComBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatNumberComBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatNumberComBoxActionPerformed

    private void ConfrimtBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfrimtBtnActionPerformed
        boolean isBooked = false;
        String selectedSeat = SeatNumberComBox.getSelectedItem().toString();
        Map<String,Customer> seatAssignment = flight.getSeatAssignment();
        for(String seat : seatAssignment.keySet()){
            if(seat.equals(selectedSeat)){
                if(seatAssignment.get(seat) != null){
                    isBooked = true;
                }
            }
        }
        if(isBooked){
            JOptionPane.showMessageDialog(null, "Seat Unavaliable!");
        }else{
            this.flight.SeatAssignment(customer, selectedSeat);

            Ticket ticket = new Ticket
            (this.flight,this.customer,SeatNumberComBox.getSelectedItem().toString(),this.travelOffice.getId());
            ticket.setPending(true);
            travelOffice.getTicketDirectory().getTicketList().add(ticket);
            JOptionPane.showMessageDialog(null, "Ticket booked!");
        }
    }//GEN-LAST:event_ConfrimtBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        cardSequenceJPanel.remove(this);
        CardLayout layout = (CardLayout) cardSequenceJPanel.getLayout();
        layout.previous(cardSequenceJPanel);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConfrimtBtn;
    private javax.swing.JComboBox<String> SeatNumberComBox;
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
