/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Lessee;

import InterfaceMain.MainJFrame;
import com.br.dao.CarDao;
import com.br.dao.OrderDao;
import com.br.dao.UserDao;
import com.br.daoImpl.CarDaoImpl;
import com.br.daoImpl.OrderDaoImpl;
import com.br.daoImpl.UserDaoImpl;
import com.br.entity.Car;
import com.br.entity.Order;
import com.br.entity.User;
import com.mysql.cj.util.StringUtils;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Alex Zhu
 */
public class AllMyOrder extends javax.swing.JPanel {
    
    private OrderDao orderDao = new OrderDaoImpl();
    private CarDao carDao = new CarDaoImpl();
    private UserDao userDao = new UserDaoImpl();
    public static String commentOrderId = null;

    /**
     * Creates new form MyOrder
     */
    public AllMyOrder() {
        initComponents();
        try {
            initTable();
        } catch (SQLException ex) {
            Logger.getLogger(AllMyOrder.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("My Order");

        btnBack.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnBack.setText("BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order Number", "Data ", "Brand", "Model", "Comment", "ifReturn"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
        jButton1.setText("Comment");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(433, 433, 433))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(148, 148, 148))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        JPanel lesseePanel = new LesseeMain();
        MainJFrame.jSplitPane1.setRightComponent(lesseePanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String id = (String)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        		if(orderDao.selectById(id).getComment() != null && !("").equals(orderDao.selectById(id).getComment())) {
        			JOptionPane.showMessageDialog(null, "the order have been commented");
        		}else {
                                commentOrderId = id;
        			Comment c = new Comment();
                                MainJFrame.jSplitPane1.setRightComponent(c);
        		}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String id = (String)jTable1.getValueAt(jTable1.getSelectedRow(), 0);
        		Boolean updateFlag = orderDao.updateReturn(id, "1");
        		if(updateFlag == true) {
        			Order o = orderDao.selectById(id);
        			Car c = carDao.selectById(o.getCarId());
        			c.setStatus_by("0");
        			carDao.updateCar(c);
        			//司机状态重置
                                if(("yes").equals(o.getNeddDriver()) ) {
                                        User d = userDao.selectById(o.getOrderDriver());
                                        if(d != null){
                                            d.setStatus_by("0");
                                            userDao.updateUser(d);
                                        }
                                }
                                JOptionPane.showMessageDialog(null, "return successfully");
                                try {
                                        initTable();
                                } catch (SQLException e1) {
                                        e1.printStackTrace();
                                }
        		}else {
        			JOptionPane.showMessageDialog(null, "retun failed");
        		}
    }//GEN-LAST:event_jButton2ActionPerformed

    @SuppressWarnings({ "unchecked", "rawtypes" })
	public void initTable() throws SQLException {
		DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
		dtm.setRowCount(0);
		ResultSet rs = orderDao.selectSelfOrder(MainJFrame.currentUser.getId());
		while (rs.next()) {
			Vector v = new Vector();
			v.add(rs.getString("id"));
			v.add(rs.getString("aviliable_time"));
			v.add(rs.getString("brand"));
			v.add(rs.getString("model"));
			if(rs.getString("comment") == null || ("").equals(rs.getString("comment"))) {
				v.add("No comments yet");
			}else {
				v.add(rs.getString("comment"));
			}
			if(("0").equals(rs.getString("if_return"))) {
				v.add("not returned");
			}else {
				v.add("returned");
			}
			dtm.addRow(v);
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
